#!/usr/bin/env python3
"""
HSV Color Segmentation Calibration Tool

An interactive tool for tuning HSV color ranges for object detection in outdoor environments.
This tool allows real-time adjustment of HSV bounds using trackbars and visualizes the
resulting mask and masked image.

Usage:
    python tools/hsv_calibrator.py [image_path]

If no image path is provided, the tool will attempt to load a default test image from
flutter_app/assets/test_images/bowls_on_green.jpg

Controls:
    - Trackbars: Adjust H_Min, H_Max, S_Min, S_Max, V_Min, V_Max
    - 's' key: Save current HSV ranges to a file
    - 'q' key: Quit the application
    - 'r' key: Reset to default ranges
"""

import cv2
import numpy as np
import sys
import os
from pathlib import Path

# Default HSV ranges (from technical analysis recommendations)
# These are robust starting points for outdoor lawn bowl detection
DEFAULT_RANGES = {
    'red_lower_1': [0, 70, 50],
    'red_upper_1': [10, 255, 255],
    'red_lower_2': [170, 70, 50],
    'red_upper_2': [179, 255, 255],
    'blue_lower': [100, 100, 50],
    'blue_upper': [140, 255, 255],
    'black_lower': [0, 0, 0],
    'black_upper': [179, 255, 40],
    'white_lower': [0, 0, 200],
    'white_upper': [179, 25, 255],
    'yellow_lower': [20, 100, 100],
    'yellow_upper': [30, 255, 255],
}

# Global variables for trackbar callbacks
h_min = 0
h_max = 179
s_min = 0
s_max = 255
v_min = 0
v_max = 255
current_image = None
hsv_image = None


def nothing(x):
    """Callback function for trackbars (required but unused)."""
    pass


def update_mask():
    """Update the mask and result images based on current trackbar values."""
    global h_min, h_max, s_min, s_max, v_min, v_max, current_image, hsv_image
    
    if current_image is None or hsv_image is None:
        return
    
    # Get current trackbar positions
    h_min = cv2.getTrackbarPos('H_Min', 'HSV Calibrator')
    h_max = cv2.getTrackbarPos('H_Max', 'HSV Calibrator')
    s_min = cv2.getTrackbarPos('S_Min', 'HSV Calibrator')
    s_max = cv2.getTrackbarPos('S_Max', 'HSV Calibrator')
    v_min = cv2.getTrackbarPos('V_Min', 'HSV Calibrator')
    v_max = cv2.getTrackbarPos('V_Max', 'HSV Calibrator')
    
    # Ensure lower bounds are <= upper bounds
    if h_min > h_max:
        h_min = h_max
        cv2.setTrackbarPos('H_Min', 'HSV Calibrator', h_min)
    if s_min > s_max:
        s_min = s_max
        cv2.setTrackbarPos('S_Min', 'HSV Calibrator', s_min)
    if v_min > v_max:
        v_min = v_max
        cv2.setTrackbarPos('V_Min', 'HSV Calibrator', v_min)
    
    # Create lower and upper bounds
    lower_bound = np.array([h_min, s_min, v_min])
    upper_bound = np.array([h_max, s_max, v_max])
    
    # Create mask
    mask = cv2.inRange(hsv_image, lower_bound, upper_bound)
    
    # Apply mask to original image
    result = cv2.bitwise_and(current_image, current_image, mask=mask)
    
    # Display mask and result
    cv2.imshow('Mask', mask)
    cv2.imshow('Result', result)
    
    # Print current values
    print(f"\rHSV Range: Lower=[{h_min:3d}, {s_min:3d}, {v_min:3d}], "
          f"Upper=[{h_max:3d}, {s_max:3d}, {v_max:3d}]", end='', flush=True)


def save_ranges():
    """Save current HSV ranges to a file."""
    global h_min, h_max, s_min, s_max, v_min, v_max
    
    filename = f"hsv_ranges_{h_min}_{s_min}_{v_min}_{h_max}_{s_max}_{v_max}.txt"
    filepath = Path(__file__).parent / filename
    
    with open(filepath, 'w') as f:
        f.write("# HSV Color Range Configuration\n")
        f.write("# Generated by HSV Calibration Tool\n\n")
        f.write(f"# Lower Bound: [{h_min}, {s_min}, {v_min}]\n")
        f.write(f"# Upper Bound: [{h_max}, {s_max}, {v_max}]\n\n")
        f.write("# Dart/Flutter DetectionConfig format:\n")
        f.write(f"lowerHsv: [{h_min}, {s_min}, {v_min}]\n")
        f.write(f"upperHsv: [{h_max}, {s_max}, {v_max}]\n\n")
        f.write("# Python/OpenCV format:\n")
        f.write(f"lower_bound = np.array([{h_min}, {s_min}, {v_min}])\n")
        f.write(f"upper_bound = np.array([{h_max}, {s_max}, {v_max}])\n")
    
    print(f"\n✓ Saved HSV ranges to: {filepath}")


def reset_to_default(color='red'):
    """Reset trackbars to default values for a specific color."""
    global h_min, h_max, s_min, s_max, v_min, v_max
    
    if color == 'red':
        lower = DEFAULT_RANGES['red_lower_1']
        upper = DEFAULT_RANGES['red_upper_1']
    elif color == 'blue':
        lower = DEFAULT_RANGES['blue_lower']
        upper = DEFAULT_RANGES['blue_upper']
    elif color == 'black':
        lower = DEFAULT_RANGES['black_lower']
        upper = DEFAULT_RANGES['black_upper']
    elif color == 'white':
        lower = DEFAULT_RANGES['white_lower']
        upper = DEFAULT_RANGES['white_upper']
    elif color == 'yellow':
        lower = DEFAULT_RANGES['yellow_lower']
        upper = DEFAULT_RANGES['yellow_upper']
    else:
        return
    
    h_min, s_min, v_min = lower
    h_max, s_max, v_max = upper
    
    cv2.setTrackbarPos('H_Min', 'HSV Calibrator', h_min)
    cv2.setTrackbarPos('H_Max', 'HSV Calibrator', h_max)
    cv2.setTrackbarPos('S_Min', 'HSV Calibrator', s_min)
    cv2.setTrackbarPos('S_Max', 'HSV Calibrator', s_max)
    cv2.setTrackbarPos('V_Min', 'HSV Calibrator', v_min)
    cv2.setTrackbarPos('V_Max', 'HSV Calibrator', v_max)
    
    update_mask()
    print(f"\n✓ Reset to default {color} ranges")


def main():
    """Main function to run the HSV calibration tool."""
    global current_image, hsv_image
    
    # Determine image path
    if len(sys.argv) > 1:
        image_path = sys.argv[1]
    else:
        # Default to test image in assets
        script_dir = Path(__file__).parent
        project_root = script_dir.parent
        image_path = project_root / 'flutter_app' / 'assets' / 'test_images' / 'bowls_on_green.jpg'
    
    # Check if image exists
    if not os.path.exists(image_path):
        print(f"Error: Image not found at {image_path}")
        print("\nUsage: python tools/hsv_calibrator.py [image_path]")
        sys.exit(1)
    
    # Load image
    print(f"Loading image: {image_path}")
    current_image = cv2.imread(str(image_path))
    
    if current_image is None:
        print(f"Error: Failed to load image from {image_path}")
        sys.exit(1)
    
    # Apply Gaussian blur (pre-processing as per best practices)
    blurred = cv2.GaussianBlur(current_image, (5, 5), 0)
    
    # Convert to HSV
    hsv_image = cv2.cvtColor(blurred, cv2.COLOR_BGR2HSV)
    
    # Create window and trackbars
    cv2.namedWindow('HSV Calibrator', cv2.WINDOW_NORMAL)
    cv2.namedWindow('Mask', cv2.WINDOW_NORMAL)
    cv2.namedWindow('Result', cv2.WINDOW_NORMAL)
    
    # Create trackbars
    cv2.createTrackbar('H_Min', 'HSV Calibrator', 0, 179, nothing)
    cv2.createTrackbar('H_Max', 'HSV Calibrator', 179, 179, nothing)
    cv2.createTrackbar('S_Min', 'HSV Calibrator', 0, 255, nothing)
    cv2.createTrackbar('S_Max', 'HSV Calibrator', 255, 255, nothing)
    cv2.createTrackbar('V_Min', 'HSV Calibrator', 0, 255, nothing)
    cv2.createTrackbar('V_Max', 'HSV Calibrator', 255, 255, nothing)
    
    # Set default values (red range 1)
    reset_to_default('red')
    
    print("\n" + "="*60)
    print("HSV Color Segmentation Calibration Tool")
    print("="*60)
    print("\nControls:")
    print("  - Adjust trackbars to tune HSV ranges")
    print("  - 's' key: Save current ranges to file")
    print("  - 'r' key: Reset to default red ranges")
    print("  - '1' key: Load red range 1 defaults")
    print("  - '2' key: Load red range 2 defaults")
    print("  - '3' key: Load blue defaults")
    print("  - '4' key: Load black defaults")
    print("  - '5' key: Load white defaults")
    print("  - '6' key: Load yellow defaults")
    print("  - 'q' key: Quit")
    print("="*60 + "\n")
    
    # Main loop
    while True:
        update_mask()
        
        key = cv2.waitKey(1) & 0xFF
        
        if key == ord('q'):
            break
        elif key == ord('s'):
            save_ranges()
        elif key == ord('r'):
            reset_to_default('red')
        elif key == ord('1'):
            reset_to_default('red')
        elif key == ord('2'):
            lower = DEFAULT_RANGES['red_lower_2']
            upper = DEFAULT_RANGES['red_upper_2']
            h_min, s_min, v_min = lower
            h_max, s_max, v_max = upper
            cv2.setTrackbarPos('H_Min', 'HSV Calibrator', h_min)
            cv2.setTrackbarPos('H_Max', 'HSV Calibrator', h_max)
            cv2.setTrackbarPos('S_Min', 'HSV Calibrator', s_min)
            cv2.setTrackbarPos('S_Max', 'HSV Calibrator', s_max)
            cv2.setTrackbarPos('V_Min', 'HSV Calibrator', v_min)
            cv2.setTrackbarPos('V_Max', 'HSV Calibrator', v_max)
            update_mask()
            print("\n✓ Loaded red range 2 defaults")
        elif key == ord('3'):
            reset_to_default('blue')
        elif key == ord('4'):
            reset_to_default('black')
        elif key == ord('5'):
            reset_to_default('white')
        elif key == ord('6'):
            reset_to_default('yellow')
    
    cv2.destroyAllWindows()
    print("\n✓ Calibration tool closed")


if __name__ == '__main__':
    main()

